on:
  push:
    branches:
      - main
jobs:
  publish-filehost-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action
      - name: Login to GitHub Container Registry
        uses: docker/login-action
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action
        with:
          push: true
          tags: |
            ghcr.io/vyladence/filehost:latest
